version: "3.8"

networks:
  pong-network:
    name: pong-network
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app
    networks:
      - pong-network

  app:
    build:
      context: ./pong_backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./pong_backend:/app
      - ./pong_backend/database.sqlite:/app/database.sqlite
    networks:
      - pong-network

volumes:
  frontend-dist:
    driver: local
    driver_opts:
      type: none
      device: ./volumes/frontend/dist
      o: bind

