networks:
    pong-network:
        name: pong-network
        driver: bridge

services:
  app:
      build:
        context: ./pong_backend
        dockerfile: dockerfile
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=production
      volumes:
        - ./pong_backend:/app
        - /app/node_modules
        - ./pong_backend/data:/app/data
      #  - ./frontend:/frontend
      networks:
        - pong-network
  nginx:
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app 
    networks:
      - pong-network
