networks:
  pong-network:
    name: pong-network
    driver: bridge

services:
  app:
    container_name: app
    build:
      context: ./pong_backend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./pong_backend:/app
      - ./pong_backend/data:/app/data
      - ./frontend:/frontend
    networks:
      - pong-network
